name: Monitor MSFT

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Get MSFT price from Yahoo
        run: |
          curl -s \
          -H "User-Agent: Mozilla/5.0" \
          -H "Accept: application/json" \
          "https://query1.finance.yahoo.com/v7/finance/quote?symbols=MSFT" > data.json

      - name: Show result
        run: cat data.json
