name: Monitor MSFT

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Call Aletheia API
        run: |
          curl "https://api.aletheiaapi.com/StockData?symbol=MSFT&apikey=${{ secrets.API_KEY }}" > data.json

      - name: Show result
        run: cat data.json
